[tool.poetry]
name = "nannyml-cloud-sdk"
version = "0.1.0"
description = "Python SDK for interacting with NannyML Cloud"
authors = [
    "Niels Nuyttens <niels@nannyml.com>",
    "Michael Van de Steene <michael@nannyml.com>"
]
readme = "README.md"
packages = [{include = "nannyml_cloud_sdk"}]

[tool.poetry.dependencies]
python = "^3.8.1"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
mypy = "^1.6.1"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
