# Generated by ariadne-codegen on 2023-10-31 15:35
# Source: graphql/queries

from typing import Dict

from .base_client import BaseClient
from .list_models import ListModels


def gql(q: str) -> str:
    return q


class Client(BaseClient):
    def list_models(self) -> ListModels:
        query = gql(
            """
            query ListModels {
              models {
                id
                name
                problemType
                createdAt
              }
            }
            """
        )
        variables: Dict[str, object] = {}
        response = self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return ListModels.model_validate(data)
