# Generated by ariadne-codegen on 2023-11-02 15:40
# Source: graphql/queries

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ColumnType


class InspectSchema(BaseModel):
    inspect_dataset: "InspectSchemaInspectDataset"


class InspectSchemaInspectDataset(BaseModel):
    columns: List["InspectSchemaInspectDatasetColumns"]


class InspectSchemaInspectDatasetColumns(BaseModel):
    name: str
    column_type: ColumnType = Field(alias="columnType")
    data_type: str = Field(alias="dataType")
    class_name: Optional[str] = Field(alias="className")


InspectSchema.model_rebuild()
InspectSchemaInspectDataset.model_rebuild()
InspectSchemaInspectDatasetColumns.model_rebuild()
