# Generated by ariadne-codegen on 2023-11-02 15:40
# Source: graphql/queries

from typing import Any, List

from pydantic import Field

from .base_model import BaseModel
from .enums import ProblemType


class ListModels(BaseModel):
    models: List["ListModelsModels"]


class ListModelsModels(BaseModel):
    id: str
    name: str
    problem_type: ProblemType = Field(alias="problemType")
    created_at: Any = Field(alias="createdAt")


ListModels.model_rebuild()
ListModelsModels.model_rebuild()
