name: Release and publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Install just
        uses: extractions/setup-just@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install python 3.12
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Build
        run: just build
      - name: Publish to PyPi
        run: uv publish
      - name: Build docs
        run: just build-docs
      - name: Publish docs
        run: just publish-docs
