name: Release and publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build docs
        run: make build-docs
      - name: Publish docs
        run: make publish-docs
